REPORT ZICONS.

TABLES: ICON.
INCLUDE <ICON>.
FIELD-SYMBOLS: <F>.

SELECT * FROM ICON.
   ASSIGN (ICON-NAME) TO <F>.
*   if ICON-BUTTON is not INITIAL.
   WRITE:   /(5) <F>, 20 '@',21 ICON-ID+1(2),23 '@',ICON-OLENG,
            ICON-BUTTON,ICON-STATUS,ICON-MESSAGE,ICON-FUNCTION,
            ICON-NAME.
*   endif.
ENDSELECT.
